# Generated by Django 5.1.6 on 2025-08-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeeweb', '0002_contactmessage_delete_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='subject',
            new_name='roll_number',
        ),
    ]
