# Generated by Django 5.1.6 on 2025-08-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeeweb', '0003_rename_subject_contactmessage_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='roll_number',
            field=models.CharField(max_length=10),
        ),
    ]
